repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        args: [--respect-gitignore]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Use an appropriate version for mypy
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports]
        # You might need to specify `files` or `types` if it tries to check too many things
        # Or configure mypy via pyproject.toml to include/exclude files
        additional_dependencies: [
          # Add any type stubs or plugins mypy needs, e.g.
          # "types-requests",
          # "pydantic" (if you use pydantic and its mypy plugin)
        ]